#!/bin/bash
#.git/hooks/post-commit
#

NOW=$(date +"%Y-%m-%d_%T")
REPO=$(basename +"$PWD")
REPOPATH=$(echo "$HOME/Dropbox/git-commit-pics/$REPO")

if [ ! -d "$HOME/Dropbox" ]; then
    echo "Cannot find Dropbox, exiting..."
    exit
fi

if [ ! -d "$REPOPATH" ]; then
    mkdir -p $REPOPATH
fi

imagesnap -q $REPOPATH/$NOW.jpg
